CREATE TABLE usuarios (id BIGINT AUTO_RANDOM PRIMARY KEY, nome VARCHAR(100), email VARCHAR(100) UNIQUE, senha_hash VARCHAR(255));
CREATE TABLE perfil (id BIGINT AUTO_RANDOM PRIMARY KEY, usuario_id BIGINT, nome_clube VARCHAR(100), escudo_url TEXT, saldo BIGINT DEFAULT 10000000);
CREATE TABLE historico (id BIGINT AUTO_RANDOM PRIMARY KEY, usuario_id BIGINT, temporada INT, titulos INT DEFAULT 0);
CREATE TABLE competicoes (id BIGINT AUTO_RANDOM PRIMARY KEY, nome VARCHAR(100), tipo VARCHAR(20), temporada INT, status VARCHAR(20));
CREATE TABLE jornal (id BIGINT AUTO_RANDOM PRIMARY KEY, titulo VARCHAR(200), conteudo TEXT, data_pub TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE mercado (id BIGINT AUTO_RANDOM PRIMARY KEY, nome_jogador VARCHAR(100), posicao VARCHAR(20), idade INT, valor BIGINT, ovr INT);
CREATE TABLE leilao (id BIGINT AUTO_RANDOM PRIMARY KEY, jogador_id BIGINT, lance_atual BIGINT, usuario_lance BIGINT, termina_em TIMESTAMP);
CREATE TABLE estadio (id BIGINT AUTO_RANDOM PRIMARY KEY, usuario_id BIGINT UNIQUE, nome VARCHAR(100), capacidade INT DEFAULT 10000, nivel INT DEFAULT 1);
